#!/bin/sh

export DB_HOST=$PGDB_PORT_5432_TCP_ADDR
export DB_PORT=$PGDB_PORT_5432_TCP_PORT
export DB_NAME=$PGDB_ENV_POSTGRES_USER
export DB_USER_NAME=$PGDB_ENV_POSTGRES_USER
export DB_USER_PASSWORD=$PGDB_ENV_POSTGRES_PASSWORD

lein start-production-server
